### ISSUE TITLE
7-gce: "npmERR! ...Parsing error:  Unexpected token :"

### ISSUE THREAD

**Issue by Anid4u2c** [GoogleCloudPlatform/nodejs-getting-started#103]
Operating System:  Windows 7* 64-bit
gcloud -v = Google Cloud SDK 146.0.0
node -v = v6.9.1
npm -v = 4.3.0

After following all the instructions for [Running the Node.js Bookshelf on Compute Engine](https://cloud.google.com/nodejs/tutorials/bookshelf-on-compute-engine), I'm getting the following error:  `C:\Program Files (x86)\Google\Cloud SDK\nodejs-getting-started\7-gce\config.js:3:15:  Parsing error:  Unexpected token :`  The error is preceded by the path to my Cloud SDK installation, and the error occurs when I run `npm test` from the nodejs-getting-started directory, and I get a similar error when I run `npm start` from the 7-gce directory.   

I'm guessing it has something to do with /7-gce/config.js ...?

One thing I noticed from the tutorial:
-   config.js comes prepared with additional configurations, yet in the tutorial when [Configuring the app](https://cloud.google.com/nodejs/tutorials/bookshelf-on-compute-engine#configuring_the_app) the instructions are to "...create a config.json file with this content:".  At first, copied config.js to config.original.js, and put the values in the existing file, and received similar errors, so then I copied and pasted (as instructed) the format that was provided.  It would be great if the tutorial, or or 7-gce README.md file clarified the recommeding procedure.  

Here is the output to the command line, from the log file:
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\__my-user-name__\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "lint"
19 error node v6.9.1
20 error npm  v4.3.0
21 error code ELIFECYCLE
22 error errno 1
23 error nodejs-getting-started@1.0.0 lint: `semistandard "**/*.js"`
23 error Exit status 1
24 error Failed at the nodejs-getting-started@1.0.0 lint script 'semistandard "**/*.js"'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the nodejs-getting-started package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     semistandard "**/*.js"
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs nodejs-getting-started
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls nodejs-getting-started
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]

**UPDATE:**  I downloaded the lasted [Node.js MSI](https://nodejs.org/en/download/) - no change in results.  I tried one more fix... when I run npm test with the config.js in it's original format (from this repository) and with my values, `npm test` is able to go one step further, than with the [format from the tutorial](https://cloud.google.com/nodejs/tutorials/bookshelf-on-compute-engine#configuring_the_app).
- npm run lint && npm run cover
- semistandard "**/*.js"
- instabul cover --hook-run-in-context node_modules/mocha/bin/__mocha --test/index.js -t 30000
After some additional output, the output indicates "You must set GCLOUD_PROJECT as an environmental variable or in config.json" - even though it is set in the config.js file.  

I really hope there is some oversight on my part, because I'm stumped!

**Comment by abek42** [comment]
Ran into a similar problem.
The tutorial (https://cloud.google.com/nodejs/getting-started/using-cloud-sql) needs to be updated.
The config.js file structure doesn't match with the instructions.
The correct process is to update the .defaults section in the config.js file:
```
 .defaults({
    // dataBackend can be 'datastore', 'cloudsql', or 'mongodb'. Be sure to
    // configure the appropriate settings for each storage engine below.
    // If you are unsure, use datastore as it requires no additional
    // configuration.
    DATA_BACKEND: 'cloudsql',

    // This is the id of your project in the Google Cloud Developers Console.
    GCLOUD_PROJECT: '[YOUR PROJECT]',

    MYSQL_USER: '[YOUR USER]',
    MYSQL_PASSWORD: '[USER PASSWORD]',
	INSTANCE_CONNECTION_NAME: '[YOUR INSTANCE CONNECTION NAME]',

    PORT: 8080
  });
```

**Comment by fhinkel** [comment]
You need to add a `config.json` file with the format given in the tutorial: 

```js
{
  "GCLOUD_PROJECT": "[YOUR_PROJECT_ID]",
  "DATA_BACKEND": "cloudsql",
  "MYSQL_USER": "[YOUR_MYSQL_USERNAME]",
  "MYSQL_PASSWORD": "[YOUR_MYSQL_PASSWORD]",
  "INSTANCE_CONNECTION_NAME": "[YOUR_INSTANCE_CONNECTION_NAME]"
}
```
