### ISSUE TITLE
2-structured-data - Post deployment Cloud SQL error: "ECONNREFUSED 127.0.0.1:3306"

### ISSUE THREAD

**Issue by jwcm488** [GoogleCloudPlatform/nodejs-getting-started#104]
After [this step](https://cloud.google.com/nodejs/getting-started/using-cloud-sql#install_the_sql_proxy#deploying_the_app_to_the_app_engine_flexible_environment) to "gcloud app deploy", the deployed app page shows this error:

> connect ECONNREFUSED 127.0.0.1:3306

This is because the socketPath is incorrect. To fix this, add the missing env variable 'NODE_ENV' into [config.js](https://github.com/GoogleCloudPlatform/nodejs-getting-started/blob/master/2-structured-data/config.js#L32), which is used by [this line](https://github.com/GoogleCloudPlatform/nodejs-getting-started/blob/master/2-structured-data/books/model-cloudsql.js#L27).

**Comment by jwcm488** [comment]
Now getting this error on deployed app page:

> connect ENOENT /cloudsql/{INSTANCE_CONNECTION_NAME} 

Works locally but not on Google App Engine. Seems like the unix socket isn't working properly from Google App Engine. Found other people with same issue online, [example](http://stackoverflow.com/questions/41971154/enoent-when-connecting-to-google-cloud-sql-from-app-engine).

**Comment by ace-n** [comment]
@jwcm488 is this still a problem for you? (If not, would you mind closing this issue?)

For what it's worth, I previously saw some flaky Google App Engine SQL connections, but those should have gone away by now.

Thanks!

**Comment by jwcm488** [comment]
No longer using Cloud SQL. Closing issue.
