### ISSUE TITLE
04-auth MEMCACHE_URL

### ISSUE THREAD

**Issue by L30Yu** [GoogleCloudPlatform/nodejs-getting-started#106]
Not working in this step.

I believe I have set the Credential correctly and I also set the MEMCACHE_URL after I created a redis from Redis Lab.

The production website is online after I depoy. But if I click login, it takes long time to loading and get 502 Bad Gateway at the end

**Comment by sravanrekandar** [comment]
+1
I too get the same error.

**Comment by bjornjo** [comment]
+1
I'm also getting the same error.
Been searching for a week on how to solve this.

Seems to be a nginx problem when handling the OAuth 2.0 session where the cookie exceeds its accepted handling size.



18:23:23.760
GET
502
568 B
120 s
Chrome 57
/auth/login?return=%2Fbooks
 130.211.3.200 - "GET /auth/login?return=%2Fbooks" 502 568 "https://zeipt-nodejs.appspot.com/books" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36"
{
 insertId: "509q3sg1g8iwlw"   
 jsonPayload: {
  trace: "$traceId"    
  latencySeconds: "120.018"    
  time: null    
 }
 httpRequest: {
  requestMethod: "GET"    
  requestUrl: "/auth/login?return=%2Fbooks"    
  status: 502    
  responseSize: "568"    
  userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36"    
  remoteIp: "130.211.3.200"    
  referer: "https://zeipt-nodejs.appspot.com/books"    
 }
 resource: {
  type: "gae_app"    
  labels: {
   project_id: "zeipt-nodejs"     
   version_id: "20170412t223708"     
   module_id: "default"     
  }
 }
 timestamp: "2017-04-18T16:23:23.760100871Z"   
 labels: {
  compute.googleapis.com/resource_name: "3337b3cedf94"    
  compute.googleapis.com/resource_id: "268767661089590486"    
  compute.googleapis.com/zone: "europe-west1-c"    
  appengine.googleapis.com/trace_id: "cfd77acb47292b0807561107d06d9ae3"    
 }
 logName: "projects/zeipt-nodejs/logs/appengine.googleapis.com%2Fnginx.request"   
}

**Comment by bjornjo** [comment]
Be sure to select "Memcached Cloud" subscription in the redis registration process, and not "Redis Cloud". 👍

**Comment by sravanrekandar** [comment]
I am using mongodb. Any ideas around it?

**Comment by sravanrekandar** [comment]
I tried Memcached Cloud. still could not see any progress.

**Comment by sravanrekandar** [comment]
After looking into the logs, I found there is an npm module ''uglify-js' is missing. It must be an internal dependency.

I have installed this 'uglify-js' and deployed the app. It is working fine now.

Details:
$ gcloud app browse
.....
Error: Cannot find module 'uglify-js'      at Function.Module._resolveFilename (module.js:469:15)      at Function.Module._load (module.js:417:25)      at Module.require (module.js:497:17)      at require (internal/module.js:20:19)      at Object.<anonymous> (/app/node_modules/jade/lib/filters.js:5:14)      at Module._compile (module.js:570:32)      at Object.Module._extensions..js (module.js:579:10)      at Module.load (module.js:487:32)      at tryModuleLoad (module.js:446:12)      at Function.Module._load (module.js:438:3)

Installation and deploying: 
$ npm install --save uglify-js
$ gcloud app deploy

**Comment by ATGardner** [comment]
They were really hiding it well, in Redis Labs site (at least it seemed that way, to the me) - I had to change from "Cloud (Hosted)" to "Memcached" at the top -
![image](https://user-images.githubusercontent.com/538720/38451986-f39dd97e-3a42-11e8-8918-506e1f2d6ca8.png)

Now I can't get the website to even load. I keep getting
[ Error: Received an ERROR response
    at Socket.error (/app/node_modules/memcached/lib/memcached.js:453:16)
    at Client.rawDataReceived (/app/node_modules/memcached/lib/memcached.js:745:51)
    at Client.BufferBuffer (/app/node_modules/memcached/lib/memcached.js:679:12)
    at Socket.bowlofcurry (/app/node_modules/memcached/lib/utils.js:126:15)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:246:13)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:607:20) ]

in the logs, and when I added some more console.log calls, I got
ERROR not allowed
from the memcache. Is there something I'm missing? am I supposed to use the SASL username/password somehow? I couldn't find any information about it anywhere.

**Comment by ATGardner** [comment]
I just had to use a complete hack to disable SASL on my Redis Labs memcached instance, to disable its SASL, just so I can run the demo. Something should be done to solve this issue properly, IMHO.

**Comment by rgilling** [comment]
I just hit this issue. I couldn't find a way to disable SASL on Redis Labs. Must be a new problem. So I had to manually update the code to use 'connect-memjs' instead of 'connect-memcached'. Then I added user name & pass to config, and where it creates the MemcachedStore add the username & password, and change from "hosts" to "servers". It's a pain because you have to do the same change on all subsequent projects.

**Comment by syediddi** [comment]
From the app, it goes to consent screen. After I select my email, the webpage displays Something Broke!

Chrome Developer tools debug says,

Failed to load resource: the server responded with a status of 500 ()

Created the memcache url, used the user name and password as it displayed in configuration

**Comment by MikeSmvl** [comment]
> From the app, it goes to consent screen. After I select my email, the webpage displays Something Broke!
> 
> Chrome Developer tools debug says,
> 
> Failed to load resource: the server responded with a status of 500 ()
> 
> Created the memcache url, used the user name and password as it displayed in configuration

Same here except it works when I use it locally and then it breaks with the same status 500() message when I deploy it.

**Comment by fhinkel** [comment]
Thanks for raising the issue. We updated the dependencies. This is what your Redis config should look like for authentication to work. 
![screen shot 2018-11-04 at 7 47 56 pm](https://user-images.githubusercontent.com/101553/47972499-d89b1f00-e06a-11e8-831c-d0b0fd4a64bb.png)
