### ISSUE TITLE
3-binary-data: Cannot upload image

### ISSUE THREAD

**Issue by srekanui** [GoogleCloudPlatform/nodejs-getting-started#107]
If I enter just form data, it is working fine. But if I try to upload image, The action is simple redirecting to 'NOT Found'.

The problem is coming i here:
//  File: lib/images.js
stream.on('error', (err) => {
    req.file.cloudStorageError = err;
    next(err);
  });

And the error is not clear: { errors: [ { domain: 'global', reason: 'notFound', message: 'Not Found' } ],
  code: 404,
  message: 'Not Found',
  response: 'Not Found' }

**Comment by sravanrekandar** [comment]
I update the repo with the changes. I found the below was the only change in the new commit. But the change didnt help much to make it work

lib/images.js
  stream.on('finish', () => {
    req.file.cloudStorageObject = gcsname;
    req.file.cloudStoragePublicUrl = getPublicUrl(gcsname);
    next();
  });

**Comment by DvdChavarri** [comment]
+1 Same Problem 

Environment:
Node v7.3.0
Npm v3.10.10
SO Windows7

Module Version:
google-cloud/datastore@1.0.1

**Comment by nicholsonjf** [comment]
I had this same issue. Here's what fixed it for me:

In config.json I changed:

`"CLOUD_BUCKET": "mybucketname"`

to:

`"CLOUD_BUCKET": "mybucketname.appspot.com"`

**Comment by fhinkel** [comment]
Thanks for raising the issue. I can't reproduce it, assuming the sources got updated in the meantime.
