### ISSUE TITLE
Missing config-default.json file in 05 and 06

### ISSUE THREAD

**Issue by RemiAWE** [GoogleCloudPlatform/nodejs-getting-started#110]
In the README of both 05 and 06, there is this line :
`Create a config.json file (copied from the config-default.json file):`
But I can't find a file named `config-default.json` in 05 nor in 06. What should I do ?

**Comment by swift-admin** [comment]
I could not find config-default.json in any folder? lost after merging?

**Comment by fhinkel** [comment]
Thanks for raising the issue. We don't have a `config-default.json` file in any of the folders. I'll update the Readmes.
