### ISSUE TITLE
Error on 6-pubsub 

### ISSUE THREAD

**Issue by raveinid** [GoogleCloudPlatform/nodejs-getting-started#136]
Error: Cannot find module '/app/node_modules/grpc/src/node/src/client.js' at Function.Module._resolveFilename (module.js:536:15) at Module._load (module.js:466:25) at loadAndPatch (/app/node_modules/@google-cloud/trace-agent/src/trace-plugin-loader.js:125:26) at Function.Module_load [as _load] (/app/node_modules/@google-cloud/trace-agent/src/trace-plugin-loader.js:159:27) at Module.require (module.js:579:17) at require (internal/module.js:11:18) at Object.<anonymous> (/app/node_modules/@google-cloud/common-grpc/src/service.js:26:12) at Module._compile (module.js:635:30) at Object.Module._extensions..js (module.js:646:10) at Module.load (module.js:554:32)

Ideas how to fix? Using Google cloud shell.

**Comment by ace-n** [comment]
Is this still an issue for you? If so, does reinstalling your Node modules (`rm -rf node_modules && npm install`) help at all?

**Comment by raveinid** [comment]
Yes, still having the same issue. Tried your work around no change.

**Comment by kjin** [comment]
As @ace-n updated the dependency on the Trace Agent recently (from 2.3.0, which had a [bug related to gRPC tracing](https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/blob/master/CHANGELOG.md#2017-10-31-version-231-beta-kjin) as you observed, to 2.4.1) this should work now. @raveinid if you're still running into issues with this, please let us know!

**Comment by fhinkel** [comment]
Hi there, thanks for reporting! Please let me know if you still run into the issue and we can reopen this.
