### ISSUE TITLE
npm error installing co-with-promise

### ISSUE THREAD

**Issue by alsfai** [GoogleCloudPlatform/nodejs-getting-started#140]
Using Node v9.3.0

npm is having an issue installing a package 'co-with-promise'. When I run npm install, it throws an ENOVERSIONS error and claims there is no valid available version of co-with-promise.

![screen shot 2018-01-06 at 11 45 20 am](https://user-images.githubusercontent.com/3261315/34643706-bd6dc0f0-f2dd-11e7-82e5-73d5ce4b91a6.png)

What is additionally confusing is that I downloaded the tutorial code, worked through up to the authentication section (section 4), had some issues, redownloaded the code and started over. When I tried to run npm install when starting over, I started to get the above error.

**Comment by fhinkel** [comment]
@alsfai thanks for raising the issue. Could you try with Node 8 or 10, as Node 9 is not supported anymore. Thanks!

**Comment by fhinkel** [comment]
Closing this for now. Please let me know if it should be reopened.
