### ISSUE TITLE
FEATURE REQUEST - function.yaml

### ISSUE THREAD

**Issue by robertjchristian** [GoogleCloudPlatform/nodejs-getting-started#145]
Would be cool to bake in support for publishing the express app (frontend described by app.yaml) to a cloud function rather than a flex instance, since this could save $$$ in real life.

I know this requires going deeper into the GCloud stack and is beyond the scope of the bookshelf app, but thought I would mention here anyway.

**Comment by fhinkel** [comment]
That would be a cool example. There's lot's of ways how one could change the architecture. I guess we'll keep it as is for now to demonstrate the capabilities of App Engine Standard.
