### ISSUE TITLE
should /kubernetes-engine be made consistent with guidance at Google's kubernetes-engine http-balancer tutorial?

### ISSUE THREAD

**Issue by gpolyn** [GoogleCloudPlatform/nodejs-getting-started#149]
Re [optional-kubernetes-engine/bookshelf-service](https://github.com/GoogleCloudPlatform/nodejs-getting-started/blob/master/optional-kubernetes-engine)/bookshelf-service.yaml), the [kubernetes-engine http-balance tutorial](https://cloud.google.com/kubernetes-engine/docs/tutorials/http-balancer) includes the following guidance:

> If you are exposing an HTTP(S) service hosted on Kubernetes Engine, HTTP(S) load balancing is the recommended method for load balancing.

Should [optional-kubernetes-engine ](https://github.com/GoogleCloudPlatform/nodejs-getting-started/blob/master/optional-kubernetes-engine) be updated, therefore, to include loading balancing via an Ingress resource, e.g., by an NGINX load balancer?

Thanks,

G

**Comment by fhinkel** [comment]
👋 Thanks for raising an issue. We will do a full rewrite on the `optional-kubernetes-engine` soon.
