### ISSUE TITLE
Tutorial 2-structured-data doesn't display properly out of the box

### ISSUE THREAD

**Issue by ATGardner** [GoogleCloudPlatform/nodejs-getting-started#151]
After `npm install` and `npm start`, when I tried accessing the webpage, I kept getting
`"Cannot read property 'start' of undefined"`

After some digging around, I updated the dependency on
"pug": "2.0.0-rc.4"
to
"pug": "2.0.0"

and everything works fine now.

**Comment by fhinkel** [comment]
Thanks for reporting! I'll update pug as soon as I have the CI running again.

**Comment by fhinkel** [comment]
Thanks for raising the issue, we updated the `pug` dependency.
