### ISSUE TITLE
ERROR: (gcloud.app.deploy) Error Response: [13] An internal error occurred during deployment.

### ISSUE THREAD

**Issue by CWSites** [GoogleCloudPlatform/nodejs-getting-started#153]
This seems to be the same issue as reported https://github.com/GoogleCloudPlatform/getting-started-java/issues/281 however since I'm using nodejs I didn't want to piggyback on the Java issue.

When running `gcloud app deploy` I get the following error.
```
ERROR: (gcloud.app.deploy) Error Response: [13] An internal error occurred during deployment.
```

My local Google cloud SDK is using the latest:
```
Google Cloud SDK 198.0.0
bq 2.0.32
core 2018.04.13
gsutil 4.30
```

**Comment by jamesarosen** [comment]
See also GoogleCloudPlatform/google-cloud-visualstudio#763 and GoogleCloudPlatform/getting-started-java#281

Some things that have helped other people:

 * upgrading to the latest gcloud suite
 * ensuring your `app.yaml` is valid (unfortunately there's no tool to validate it and the error doesn't tell you if this is the problem)
 * running `gcloud config set app/use_deprecated_preparation True`
 * adding `- ^node_modules/.*$` to the list of `skip_files` in your `app.yaml`

**Comment by CWSites** [comment]
Thanks, the last bullet that you mentioned is what fixed it for me.

**Comment by nhuttrung** [comment]
We got the same issue as described below.
I and my colleague follow https://cloud.google.com/appengine/docs/standard/nodejs/quickstart

1. I (as project owner) can deploy successfully.

2. However, my colleague got an error "[13] An internal error occurred" when trying to deploy. 
His roles are App Engine Admin, Storage Object Admin
The log of `gcloud app deploy --verbosity=debug` : 

....
DEBUG: Operation [apps/my_project/operations/76514661-53ac-4f9e-9a2c-c24a417bd487] not complete. Waiting to retry.
Updating service [my_service].../DEBUG: Operation [apps/my_project/operations/76514661-53ac-4f9e-9a2c-c24a417bd487] not complete. Waiting to retry.
Updating service [my_service]...\DEBUG: Operation [apps/my_project/operations/76514661-53ac-4f9e-9a2c-c24a417bd487] not complete. Waiting to retry.
Updating service [my_service]...-DEBUG: Operation [apps/my_project/operations/76514661-53ac-4f9e-9a2c-c24a417bd487] complete. Result: {
    "metadata": {
        "user": "myemail@gmail.com",
        "target": "apps/my_project/services/my_service/versions/v100",
        "@type": "type.googleapis.com/google.appengine.v1.OperationMetadataV1",
        "insertTime": "2018-09-06T12:40:49.605Z",
        "method": "google.appengine.v1.Versions.CreateVersion"
    },
    "done": true,
    "name": "apps/my_project/operations/76514661-53ac-4f9e-9a2c-c24a417bd487",
    "error": {
        "message": "An internal error occurred.",
        "code": 13
    }
}
Updating service [my_service]...failed.
DEBUG: (gcloud.app.deploy) Error Response: [13] An internal error occurred.

**Comment by iatomic** [comment]
I am having very same isssue. I find e quality of gcloud software to be pathetic

**Comment by sudhiry** [comment]
We also got the same issue for nodejs deployment:
```
Updating service [default] (this may take several minutes)...-DEBUG: Operation [apps/sample/operations/d917de39-d60d-42ec-8f07-0fs60b5e351d] complete. Result: {
    "metadata": {
        "target": "apps/sample/services/default/versions/20181024t001730",
        "method": "google.appengine.v1.Versions.CreateVersion",
        "user": "<myemail>",
        "insertTime": "2018-10-23T18:49:41.651Z",
        "endTime": "2018-10-23T18:50:16.315Z",
        "@type": "type.googleapis.com/google.appengine.v1.OperationMetadataV1"
    },
    "done": true,
    "name": "apps/sample/operations/d917de39-d60d-42ec-8f07-0fs60b5e351d",
    "error": {
        "message": "An internal error occurred during deployment.",
        "code": 13
    }
}
```

Version:
Google Cloud SDK 221.0.0
bq 2.0.35
core 2018.10.12
gsutil 4.34

Interestingly, what I found is below:
- if we keep app.yaml simple as below, the deployment works!
```
runtime: nodejs
env: flex
```
- if we add additional parameters like below, the deployment fails! 👎 
```
runtime: nodejs
env: flex
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 10
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.9
resources:
  cpu: 2
  memory_gb: 4.0
  disk_size_gb: 5
```
Currently I don't have tool for validation of app.yaml, so please share if anybody have it.

Thanks.

**Comment by mrfambo** [comment]
Such a pathetic response from Google :/ No any solution anywhere !!!
