### ISSUE TITLE
Issues with 7-gce example

### ISSUE THREAD

**Issue by abek42** [GoogleCloudPlatform/nodejs-getting-started#169]
Again, doesn't run out of the box.

Updates needed for 7-gce/gce/startup-script.sh:
->PROJECT_ID step on Line 20 fails causing git repo clone failure on line 43
->Line 45: Call to install node.js version uses an outdated version which fails to install on debian-8

Tutorial doesn't mention the need to enable Google+ Social API (for the login part of example)
Similarly, it doesn't ask to create a Datastore which is used by the application.

**Comment by abek42** [comment]
Further issues:
Deployment on GCE fails when using F1-micro (grpc module not found errors), requires n1-standard-1 to install
The login part of the example doesn't run on GCE (works locally), need more information on how to configure it for GCE
The MEMCACHE_URL setting in config.js to localhost:11211 requires edits to startup script to explicitly pull memcached (through apt-get install)

Can someone from the dev team actually step through the whole tutorial and see if it actually works as described in the tutorial? After nearly 35 deployments, I haven't managed to get this example to fully work on GCE.

**Comment by npomfret** [comment]
@abek42 what fails when running on an f1-micro?

**Comment by npomfret** [comment]
The script clones the git repo. Will this not error as soon as the machine is rebooted (because the repo will already be cloned)?
