### ISSUE TITLE
Unsatisfied Memcached dependency in Kubernetes Quickstart

### ISSUE THREAD

**Issue by martin-haynes** [GoogleCloudPlatform/nodejs-getting-started#170]
The getting started demo **optional-kubernetes-engine** fails with a runtime error when deployed with the default configuration specified in `bookshelf-frontend-datastore.yaml`

`Error: connect ECONNREFUSED 127.0.0.1:11211"`

This is due to an unsatisfied dependency on a local memcached service within the cluster.

The frontend application includes conditional logic to select between production and non-production session stores:

```
// In production use the App Engine Memcache instance to store session data,
// otherwise fallback to the default MemoryStore in development.
if (config.get('NODE_ENV') === 'production' && config.get('MEMCACHE_URL')) {
  sessionConfig.store = new MemcachedStore({
    hosts: [config.get('MEMCACHE_URL')]
  });
}
```

However, sessionConfig.store is _always initialized_ when following the quickstart demo. This seems to be due to the fact that the Kubernetes runtime sets the **NODE_ENV** environment variable to **production** by default within the kubernetes engine managed service, just as it does in the [App Engine Flexible Environment](https://cloud.google.com/appengine/docs/flexible/nodejs/runtime#environment_variables)

Ideally either the project documentation is updated to describe how to deploy in dev mode or the k8s frontend deployment configuration is revised to explicitly default to 'dev'.

```
        env:
          - name: PROJECT_ID
            value: [GCLOUD_PROJECT]
          - name: NODE_ENV
            value: dev
```

**Comment by fhinkel** [comment]
Sorry, the documentation is unclear. You have to either delete the `MEMCACHE_URL` entry from `config.js`, or add a real endpoint in `config.json`. See the chapter on [authenticating users](https://cloud.google.com/nodejs/getting-started/authenticate-users).
