### ISSUE TITLE
Outdated dependency

### ISSUE THREAD

**Issue by fhinkel** [GoogleCloudPlatform/nodejs-getting-started#181]
`sinon` brings in `text-encoding`, which is no longer maintained.

```
nodejs-docs-samples/appengine/hello-world/standard (master)$ npm i
npm WARN deprecated text-encoding@0.6.4: no longer maintained
```

```
appengine-hello-world@0.0.1 /Users/franzih/code/gcp/nodejs-docs-samples/appengine/hello-world/standard
└─┬ @google-cloud/nodejs-repo-tools@2.3.5
  └─┬ sinon@6.0.1
    └─┬ nise@1.4.5
      └── text-encoding@0.6.4
```

**Comment by fstanis** [comment]
I think this should be filed with [nodejs-repo-tools](https://github.com/GoogleCloudPlatform/nodejs-repo-tools).

**Comment by JustinBeckwith** [comment]
Tracking bug for the dependency update in nise here:
https://github.com/sinonjs/nise/issues/66

**Comment by JustinBeckwith** [comment]
Of course! Mostly adding this because I had to track it down in my repos too :)

**Comment by fhinkel** [comment]
Isn't there an option now to transfer issues to a different repo?
