### ISSUE TITLE
a couple typos in the startup script

### ISSUE THREAD

**Issue by broady** [GoogleCloudPlatform/nodejs-getting-started#22]
https://github.com/GoogleCloudPlatform/nodejs-getting-started/blob/master/gce/startup-script.sh#L22
`-` `The monitor will automatically pickup logs send to`
`+` `The monitor will automatically pick up logs sent to`

https://github.com/GoogleCloudPlatform/nodejs-getting-started/blob/master/gce/startup-script.sh#L30
`-` `apt=get update`
`+` `apt-get update`

**Comment by jonparrott** [comment]
Fixed, thanks.
