### ISSUE TITLE
Unable to connect to Cloud SQL

### ISSUE THREAD

**Issue by jduval** [GoogleCloudPlatform/nodejs-getting-started#24]
I can't connect from App Engine to Cloud SQL by unix socket nor by TCP.

```js
var mysql = require('mysql');
var mysqlConf = {
  user: 'root',
  password: '',
  socketPath: '/cloudsql/<appli-id>:<instance>',
  database: 'myDb'
};

connection = mysql.createConnection(mysqlConf);

connection.connect(function(err) {
  if (err)
    return callback(err);
  return callback();
});
```
it throws : 

```js
   Error: connect ENOENT
        at exports._errnoException (util.js:746:11)
        at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1000:19)
```

I'm using Nodejs 4.1.1.

Also I have no problem to connect to Cloud SQL from my localhost through TCP.

Am I missing something?

**Comment by jonparrott** [comment]
For Managed VMs, the unix socket to connect to Cloud SQL is unavailable. For now, you must use the Cloud SQL instance's public IP address. See the section on configuring the Cloud SQL instance on [this page of the tutorial](https://cloud.google.com/nodejs/getting-started/using-cloud-sql#download_app).

I'm going to go ahead and close this issue. If you have any further questions, please feel free to comment and I'll be happy to help.

**Comment by raz3r** [comment]
Is this still a thing or can I use the socket now? Thanks.

**Comment by mm-wang** [comment]
Can someone post an example of using a socketPath that uses TCP and Google Cloud SQL with a proxy?

**Comment by jmdobry** [comment]
It's on our roadmap to update this repo to do just that (in the next week or two).

**Comment by mm-wang** [comment]
Any chance you could give a preview? :). I have a connection working locally through a cloudsqlproxy to my database, but not when I host my application externally on Heroku.

I have something along the lines of:

```
function getConnection(){
   return mysql.createConnection({
      host: "127.0.0.1",
      user: [username],
      password: [password],
      //socketPath: "/cloudsql/[instance-connection-name]" 
      //commented out because it is not currently working
   });
}

var connection = getConnection();
connection.query([sample query], function(err, rows, fields){
   ...
})
```

and I invoke the proxy from the root of the folder using the command on a Windows machine:
```
cloud_sql_proxy.exe -dir=/cloudsql -instances=[instance-connection-name]=tcp:3306 & mysql -u [username] -p [password] -h 127.0.0.1
```

Is it just the syntax of the socketPath? Or is there more that I'm missing about how the cloudsqlproxy executable needs to run?

**Comment by ahamid** [comment]
Is this still broken? Everyone on the internet trying to follow the provided sample project and tutorials seems to be confused about this.

**Comment by jmdobry** [comment]
This is probably a better tutorial for connecting to Cloud SQL: https://cloud.google.com/appengine/docs/flexible/nodejs/using-cloud-sql
