### ISSUE TITLE
Tutorial 2-structured-data - Internal Server Error

### ISSUE THREAD

**Issue by akupiec** [GoogleCloudPlatform/nodejs-getting-started#242]
Fallowing tutorial on newly created project, after successful deploy there is only "Internal Server Error"

In app engine current version logs there is such error:

Error: 7 PERMISSION_DENIED: Missing or insufficient permissions.
    at Object.exports.createStatusError (/srv/node_modules/grpc/src/common.js:87:15)
    at Object.onReceiveStatus (/srv/node_modules/grpc/src/client_interceptors.js:1188:28)
    at InterceptingListener._callNext (/srv/node_modules/grpc/src/client_interceptors.js:564:42)
    at InterceptingListener.onReceiveStatus (/srv/node_modules/grpc/src/client_interceptors.js:614:8)
    at callback (/srv/node_modules/grpc/src/client_interceptors.js:841:24)

Do anyone known what is the reason of this error ?

**Comment by fhinkel** [comment]
Hi, thanks for raising the issue. Did you follow the setup instructions and enable the required APIs?

**Comment by fhinkel** [comment]
I just tried tutorial 2. What does your `config.json` look like?

**Comment by akupiec** [comment]
config.json I had created according to tutorial with own project id
```
{
  "GCLOUD_PROJECT": "something-something-333",
  "DATA_BACKEND": "datastore"
}
```

In the end I did manage to successfully deploy and run [sahat/hackathon-starter](https://github.com/sahat/hackathon-starter)
I'm not sure now what exactingly was the case, but I thing it was one of fallowing:
* package.json
```
"engines": {
  "node": "10",
  "npm": ">=5.6.0"
}
```
* app.yaml
```
runtime: nodejs
env: flex
manual_scaling:
  instances: 1
```
* or enabling "Compute Engine" (I'm not sure when, and if I activated it, or it's activated by default, or it activated itself in one of my invalid configurations)

The most problematic from my perspective was error message, which wasn't telling anything specific more than "PERMISSION_DENIED"

**Comment by fhinkel** [comment]
Glad you got it running. Could you try to use this `app.yaml`: 

```
runtime: nodejs10
```

That will use AppEngine Standard instead of Flex, which is much faster to deploy to. Thank you!

**Comment by akupiec** [comment]
Thank you @fhinkel! It indeed worked with just this single line in app.yaml

**Comment by fhinkel** [comment]
Awesome. I'm closing this. Let me know if you run into more issues.
