### ISSUE TITLE
Why require users to set GCLOUD_PROJECT?

### ISSUE THREAD

**Issue by steren** [GoogleCloudPlatform/nodejs-getting-started#247]
The current project is accessible in App Engine the the `GOOGLE_CLOUD_PROJECT` environment variable.

It is not clear why we ask users to set `GCLOUD_PROJECT` in `config.js`.
Or, if not set, why we do not fallback to the `GOOGLE_CLOUD_PROJECT` environment variable.

**Comment by fhinkel** [comment]
Good catch. I guess we wanted the config file to determine which project is used rather than rely on environment variables.

**Comment by steren** [comment]
But what is the rationale? 
This adds unnecessary friction to the sample.

**Comment by fhinkel** [comment]
I misunderstood. I guess there was a reason in the past to set it up like this. I'll work on changing it. The docs around `config.json` are outdated and need to be fixed, too.

**Comment by fhinkel** [comment]
Obsolete with planned rewrite of the tutorial.
