### ISSUE TITLE
Convert tests from ava to mocha

### ISSUE THREAD

**Issue by AVaksman** [GoogleCloudPlatform/nodejs-getting-started#254]
The following list represents all files that currently use `ava` and need to be updated to use `mocha`:

1. - [ ] 1-hello-world/package.json
2. - [ ] 2-structured-data/test/app.test.js
3. - [ ] 2-structured-data/test/cloudsql.test.js
4. - [ ] 2-structured-data/test/datastore.test.js
5. - [ ] 2-structured-data/test/_api-tests.js
6. - [ ] 2-structured-data/test/_crud-tests.js
7. - [ ] 3-binary-data/test/app.test.js
8. - [ ] 3-binary-data/test/cloudsql.test.js
9. - [ ] 3-binary-data/test/datastore.test.js
10. - [ ] 3-binary-data/test/_api-tests.js
11. - [ ] 3-binary-data/test/_crud-tests.js
12. - [ ] 4-auth/test/app.test.js
13. - [ ] 4-auth/test/cloudsql.test.js
14. - [ ] 4-auth/test/datastore.test.js
15. - [ ] 4-auth/test/oauth2.test.js
16. - [ ] 4-auth/test/_api-tests.js
17. - [ ] 4-auth/test/_crud-tests.js
18. - [ ] 5-logging/test/app.test.js
19. - [ ] 5-logging/test/cloudsql.test.js
20. - [ ] 5-logging/test/datastore.test.js
21. - [ ] 5-logging/test/oauth2.test.js
22. - [ ] 5-logging/test/_api-tests.js
23. - [ ] 5-logging/test/_crud-tests.js
24. - [ ] 6-pubsub/test/app.test.js
25. - [ ] 6-pubsub/test/background.test.js
26. - [ ] 6-pubsub/test/cloudsql.test.js
27. - [ ] 6-pubsub/test/datastore.test.js
28. - [ ] 6-pubsub/test/oauth2.test.js
29. - [ ] 6-pubsub/test/worker.test.js
30. - [ ] 6-pubsub/test/_api-tests.js
31. - [ ] 6-pubsub/test/_crud-tests.js
32. - [ ] 7-gce/test/app.test.js
33. - [ ] 7-gce/test/background.test.js
34. - [ ] 7-gce/test/cloudsql.test.js
35. - [ ] 7-gce/test/datastore.test.js
36. - [ ] 7-gce/test/mongodb.test.js
37. - [ ] 7-gce/test/oauth2.test.js
38. - [ ] 7-gce/test/worker.test.js
39. - [ ] 7-gce/test/_api-tests.js
40. - [ ] 7-gce/test/_crud-tests.js
41. - [ ] optional-kubernetes-engine/test/app.test.js
42. - [ ] optional-kubernetes-engine/test/background.test.js
43. - [ ] optional-kubernetes-engine/test/cloudsql.test.js
44. - [ ] optional-kubernetes-engine/test/datastore.test.js
45. - [ ] optional-kubernetes-engine/test/mongodb.test.js
46. - [ ] optional-kubernetes-engine/test/oauth2.test.js
47. - [ ] optional-kubernetes-engine/test/worker.test.js
48. - [ ] optional-kubernetes-engine/test/_api-tests.js
49. - [ ] optional-kubernetes-engine/test/_crud-tests.js

**Comment by fhinkel** [comment]
@AVaksman The PRs all have merge conflicts. Can you please resolve them so we can run the tests and merge. Thank you.
