### ISSUE TITLE
Use node-fetch instead of repo-tools.getRequest

### ISSUE THREAD

**Issue by fhinkel** [GoogleCloudPlatform/nodejs-getting-started#268]
Let's replace `require('@google-cloud/nodejs-repo-tools').getRequest` with `node-fetch`.

**Comment by hpandeycodeit** [comment]
@fhinkel I can work on this. 

Do you mean to replace this ` require('@google-cloud/nodejs-repo-tools').getRequest ` with `node-fetch` everywhere?

**Comment by fhinkel** [comment]
@hpandeycodeit  👋 Yes, but there's some tricky logic in `getRequest()` that we're using in the tests. We need to be careful not to break that.
