### ISSUE TITLE
what's the nodejs version of the nodejs runtime?

### ISSUE THREAD

**Issue by yangaobo** [GoogleCloudPlatform/nodejs-getting-started#29]
what will be the version used in the vm by setting `runtime: nodejs` in **app.yaml**?
Will it refer my **package.json** for the version?
If no, any ways that I can config it except using custom Docker?

**Comment by jonparrott** [comment]
Currently, `0.12.7` is the default. You can look at the runtime's base docker image [here](https://github.com/GoogleCloudPlatform/nodejs-docker).

The runtime should also respect whatever you specify in the `engines` field in `package.json`. Note that the runtime is in beta, so if you do run into issues with that people file a bug on the [runtime's repository](https://github.com/GoogleCloudPlatform/nodejs-docker).
