### ISSUE TITLE
ERROR: (gcloud.app.deploy) INTERNAL: Internal error encountered.

### ISSUE THREAD

**Issue by ChiKaLiO** [GoogleCloudPlatform/nodejs-getting-started#320]
> $ gcloud app deploy

> ERROR: (gcloud.app.deploy) INTERNAL: Internal error encountered.

everything was working just commented some lines and rebuild angular got this..

**Comment by fhinkel** [comment]
👋 @ChiKaLiO Thanks for reporting the issue. On which chapter did you encounter this problem? Sometimes `gcloud.app.deploy` returns an error if the `package.json` file is broken or contains dependencies that are not on npm.

**Comment by ChiKaLiO** [comment]
@fhinkel  i literally done nothing.. and after a day it worked..

**Comment by fhinkel** [comment]
So weird, glad you got it to work!
