### ISSUE TITLE
Package name "nodejs-getting-started" used in multiple packages:

### ISSUE THREAD

**Issue by mozgbrasil** [GoogleCloudPlatform/nodejs-getting-started#326]
Hello good afternoon

See this exception is triggered because the packages have the same names, I suggest changing the names for each "package.json"

Package name "nodejs-getting-started" used in multiple packages:

![Captura de tela de 2019-06-27 13-15-10](https://user-images.githubusercontent.com/17202780/60282605-bbf37600-98dd-11e9-9376-832943e24e39.png)

**Comment by mozgbrasil** [comment]
Hello good afternoon brother

Note that by changing the names for each "package.json" the lerna works as expected

![Uploading Captura de tela de 2019-06-27 13-19-58.png…]()
![Captura de tela de 2019-06-27 13-20-22](https://user-images.githubusercontent.com/17202780/60282892-581d7d00-98de-11e9-987d-1a0dd09d0966.png)

**Comment by fhinkel** [comment]
@mozgbrasil Thanks for raising the issue. I'll look into changing it so `lerna` runs without issues.

**Comment by mozgbrasil** [comment]
Hi brother, thanks for interacting.
