### ISSUE TITLE
Replace 5 with greetings.length (or the js equivalent).

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/nodejs-getting-started#331]
https://github.com/GoogleCloudPlatform/nodejs-getting-started/blob/e8af221f4bfb0abfc59bf037051ec4e912104d8f/sessions/index.js#L28

**Comment by fhinkel** [comment]
Fixed in https://github.com/GoogleCloudPlatform/nodejs-getting-started/pull/335
