### ISSUE TITLE
Incorrect Kokoro configuration prevents auto-linter presubmit from running

### ISSUE THREAD

**Issue by feywind** [GoogleCloudPlatform/nodejs-getting-started#359]
The Kokoro configuration file for linting (lint.cfg) lists lint.sh as being under .kokoro/, but it is actually under .kokoro/presubmit/.

**Comment by fhinkel** [comment]
@feywind did this get fixed with your PR?

**Comment by feywind** [comment]
Almost certainly yes, but also I can't find the PR... which is weird. Let me look a bit more.

**Comment by feywind** [comment]
Here it is. I'm not sure why it didn't get linked, but yeah, we can close this.
https://github.com/GoogleCloudPlatform/nodejs-getting-started/pull/360
