### ISSUE TITLE
Wondering::  books/api.js for What? 

### ISSUE THREAD

**Issue by bexoss** [GoogleCloudPlatform/nodejs-getting-started#36]
Hello, I'm learning 'mean' stack theseday,  I follow google cloud node.js start guide line, so I made sample application using your codes. I have to delve into codes, to know how it works. 

But, I don't know why books/api.js comes up. Is this just an api? I delete it and test at local, but It doesn't matters. Can you explain its roles?

**Comment by rainvillem** [comment]
I suggest you to read on how node.js works
The app.js is the entry point of this node.js application.  
This entry point is define in package.json under scripts start as "node app.js"

**Comment by stephenplusplus** [comment]
@bexoss asked about books/api.js, not app.js. It doesn't look like it's used, but it's possibly a mocked backend for the Google Books API.

**Comment by jonparrott** [comment]
Neither. :)

It's just a simple REST API interface to the bookshelf application. It does the same as `crud.js`.

(I'm closing this issue, but feel free to continue to comment on it)
