### ISSUE TITLE
testing: enable the Build Cop Bot

### ISSUE THREAD

**Issue by tbpg** [GoogleCloudPlatform/nodejs-getting-started#379]
Instructions here: https://github.com/googleapis/repo-automation-bots/tree/master/packages/buildcop

**Comment by tbpg** [comment]
I installed the bot on the repo (first step of the instructions). We still need to call the `buildcop` binary to publish the test logs.

**Comment by tbpg** [comment]
Related: #1615.

**Comment by fhinkel** [comment]
Fixed by https://github.com/GoogleCloudPlatform/nodejs-getting-started/pull/409
