### ISSUE TITLE
Enable CI for tests

### ISSUE THREAD

**Issue by fhinkel** [GoogleCloudPlatform/nodejs-getting-started#388]
The tests in 
* https://github.com/GoogleCloudPlatform/nodejs-getting-started/tree/master/authenticating-users
* https://github.com/GoogleCloudPlatform/nodejs-getting-started/tree/master/bookshelf
* https://github.com/GoogleCloudPlatform/nodejs-getting-started/tree/master/sessions 
are currently not run. We need to enable them for presubmit and release. 

cc @JustinBeckwith

**Comment by sofisl** [comment]
See PR #405 and the directory for CL/315341877
