### ISSUE TITLE
You can't throw from async functions without a catch block

### ISSUE THREAD

**Issue by Hoppingmad9** [GoogleCloudPlatform/nodejs-getting-started#488]
In [firestore.js](https://github.com/GoogleCloudPlatform/nodejs-getting-started/blob/master/bookshelf/books/firestore.js) on line 77.
```
async function read(id) {
  const doc = await db.collection(collection).doc(id).get();

  if (!doc.exists) {
    throw new Error('No such document!');
  }
  return doc.data();
}
```
If the doc doesn't exist then it will result in a 

> UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

warning.

**Comment by meredithslota** [comment]
(Sorry for the back-and-forth labeling — this isn't about the Firestore API, per se, but rather about a .js file named firestore.js which includes sample code for the`bookshelf` sample application.)

**Comment by bcoe** [comment]
@Hoppingmad9 this structure is intentional, if someone is using this sample code, you would do so like this:

```js
try {
  catch await read(id);
} catch (err) {
  // recover from error.
}
```
