### ISSUE TITLE
Error with command: npm test

### ISSUE THREAD

**Issue by mohamedmehdigara** [GoogleCloudPlatform/nodejs-getting-started#498]
![Capture](https://user-images.githubusercontent.com/47916299/149304125-cee53f67-4ea9-48ae-a965-6e41d0f292e9.PNG)

**Comment by SurferJeffAtGoogle** [comment]
Running the test requires some set up.  The instructions in the error message explain the set up steps.  Please run `gcloud config set project <my GCP project>`.
