### ISSUE TITLE
Error with command: gcloud config set project background

### ISSUE THREAD

**Issue by mohamedmehdigara** [GoogleCloudPlatform/nodejs-getting-started#499]
![image](https://user-images.githubusercontent.com/47916299/149478780-fed87fdc-9de1-4b1a-82cf-fc3a95113264.png)

**Comment by SurferJeffAtGoogle** [comment]
I see the same:

```
PS > gcloud config set project background
Updated property [core/project].
WARNING: You do not appear to have access to project [background] or it does not exist.
```

I believe gcloud is behaving as expected.

How did you expect gcloud to behave?
