### ISSUE TITLE
Add a note explaining why kerberos is a dependency

### ISSUE THREAD

**Issue by cesarandreu** [GoogleCloudPlatform/nodejs-getting-started#52]
It seemed like an unused dependency, and when I searched the repo I couldn't find any mention of what it was for. After googling it, I found out it was apparently required by mongodb for some systems?

I think making a note of that in the structured data tutorial would be helpful.

**Comment by ace-n** [comment]
I don't think this needs a separate note (outside of perhaps `package.json`), and adding one would detract from the conciseness of the tutorial. (Also, specifying it in `package.json` means that no additional effort is required on the user's part - they have to type `npm install` anyway, whether this note is there or not.)

You're correct that Kerberos is sometimes required by MongoDB - more information about that [here].
