### ISSUE TITLE
npm install fails on Windows

### ISSUE THREAD

**Issue by cyrfer** [GoogleCloudPlatform/nodejs-getting-started#58]
I am not having an easy time following the [tutorial](https://cloud.google.com/nodejs/getting-started/using-cloud-datastore#run_the_app_on_your_local_computer)

## My system
* Windows 10 x64
* All visual studio packages possible installed (not really, but I at least installed 2015 several times)
* Node 6.2, NPM 3.8.9
* I also tried Node 4.4.4 because of [this note](https://github.com/grpc/grpc/issues/6338) and saw issues with `sse4_crc32` when rebuilding node-gyp.

## NPM install Errors
* I attached the log file. Seems related to gprc.
* Some shell output:

node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\johnk_000\\Documents\\google-cloud-platform\\nodejs-getting-started\\2-structured-data\\node_modules\\grpc\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\johnk_000\Documents\google-cloud-platform\nodejs-getting-started\2-structured-data\node_modules\grpc
node-pre-gyp ERR! node -v v6.2.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.25
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\Users\johnk_000\Documents\google-cloud-platform\nodejs-getting-started\2-structured-data\node_modules\grpc\src\node\extension_binary\grpc_node.node --module_name=grpc_node --module_path=C:\Users\johnk_000\Documents\google-cloud-platform\nodejs-getting-started\2-structured-data\node_modules\grpc\src\node\extension_binary' (1)
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm
[npm-debug.zip](https://github.com/GoogleCloudPlatform/nodejs-getting-started/files/276602/npm-debug.zip)
 ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE

npm ERR! grpc@0.13.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@0.13.1 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the grpc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs grpc
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls grpc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\johnk_000\Documents\google-cloud-platform\nodejs-getting-started\2-structured-data\npm-debug.log

**Comment by cyrfer** [comment]
Fixed by helping npm know which version of VC++ to use.

> npm config set msvs_version 2015 --global

**Comment by ace-n** [comment]
Closing - gRPC is now publishing precompiled binaries for Node 6, so there's no longer a (significant) need to build them manually.
