### ISSUE TITLE
model-datastore has incorrect syntax for pulling books that are "mine"

### ISSUE THREAD

**Issue by lowagner** [GoogleCloudPlatform/nodejs-getting-started#59]
the syntax in the current file books/model-datastore.js is
```
  var q = ds.createQuery([kind])
    .filter('createdById =', userId)
    ...
```
but should instead be (note the filter):
```
  var q = ds.createQuery([kind])
    .filter('createdById', '=', userId)
    ...
```
unless support for the former way will appear in the google datastore API.

**Comment by ace-n** [comment]
Fixed by #78 - thanks for reporting!
