### ISSUE TITLE
http://localhost:8080 preview displays "Login Required"

### ISSUE THREAD

**Issue by MattCowski** [GoogleCloudPlatform/nodejs-getting-started#6]
Doesn't mention any auth steps in tutorial

**Comment by jonparrott** [comment]
Hi @MattCowski, which step of the tutorial are you on? What operating system are you using?

**Comment by MattCowski** [comment]
Wow, fast reply! So, I figured it out -- I needed to `gcloud auth login`.

**Comment by jonparrott** [comment]
Glad to hear.
