### ISSUE TITLE
Add service: service_name

### ISSUE THREAD

**Issue by hhhonzik** [GoogleCloudPlatform/nodejs-getting-started#64]
Hey,

Just a quick note about those sample codes. GCP doesn't allow you to delete **default** service, but all samples creates one.

I'd suggest adding `service: service_name` to each of those samples, so we can delete all created instances and start fresh. 

I am happy to do a PR for it.

**Comment by ace-n** [comment]
The starter projects are not necessarily intended to be reused out of the box.

However, it's easy enough to reuse the **default** service - deploy a new version of your app, then delete the old versions.
