### ISSUE TITLE
Store sessions in a centralized database

### ISSUE THREAD

**Issue by yankustefan** [GoogleCloudPlatform/nodejs-getting-started#8]
The tutorial mentions at "Authenticate users / Understand the Code" that sessions should be stored in a centralized database.

> In production, you should use a centralized database to store sessions securely. Google Cloud Platform makes it easy to deploy many databases, including Redis or Memcache.
https://cloud.google.com/nodejs/getting-started/authenticate-users#about_sessions

May I ask you for some help and clarify why I should do this, and how that would be implemented in the current example?

For example does it mean not to use the nodejs cookie-session module at all, or, does it just mean that sensitive information should not be stored in the local cookie but on the remote database?

**Comment by jonparrott** [comment]
> does it just mean that sensitive information should not be stored in the local cookie but on the remote database?

Exactly, you shouldn't store any information on the user's computer that you don't want them to have access too. In the sample, the application is storing only the user's profile information, which they should already know, so storing the session in the cookie is fine. However, if there is additional information you want to store in the session but don't want the user to see (such as rate-limiting information), then you should use a server-side data store.

One easy example is to switch from express-cookie-session over to [connect-redis](https://github.com/tj/connect-redis). You can deploy a redis server/cluster on GCE easily with [Click-to-Deploy](https://cloud.google.com/solutions/redis/click-to-deploy). If you're using Mongo, there's also a mongodb backend. We also have a [datastore backend](https://github.com/GoogleCloudPlatform/cloud-datastore-session-node), but using a replicated database like datastore is slower than using an in-memory cache like Redis.

**Comment by yankustefan** [comment]
Thank you very much for your input!
