### ISSUE TITLE
Update samples to use latest version of @google-cloud/datastore

### ISSUE THREAD

**Issue by atn832** [GoogleCloudPlatform/nodejs-getting-started#84]
Could you update those sample projects to show how to use the latest version of the Datastore API?

The sample code works fine with @google-cloud/datastore v0.1.1, but not the latest (v0.5.0). It crashes when trying to deserialize the object id's.

**Comment by ace-n** [comment]
@atn832 thanks for reporting - this is already on our roadmap. (See #80 - and feel free to follow up there if you have any questions.)
